[Task 3 API Design & Framework] Set up FE.
JuliaKholodetska/Task3-Full-Stack-JS-Internship pull request #1
Opened 2021-03-22 16:54 UTC by JuliaKholodetska

2021-03-23 09:05 UTC, MariiaKolisnyk requested changes
- I suggest re-thinking the project file structure. 
- the image formats are strange. 
- why are there 2 `index.html` files in your project?
- I do not see the root element

2021-03-23 09:05 UTC, MariiaKolisnyk commented on client/src/screens/HomeScreen.js
> +import React from 'react'
Are `screens` common units for React App?

2021-03-23 09:07 UTC, MariiaKolisnyk commented
typo
![image](https://user-images.githubusercontent.com/30797461/112121464-f4fe6e80-8bc7-11eb-8c96-aff388e5b378.png)

2021-03-23 09:09 UTC, MariiaKolisnyk commented
please, remove `node_modules` from the repo and add this folder to `.gitignore`. we never push them to repos.

2021-03-23 09:14 UTC, MariiaKolisnyk commented
I'm not aware of file naming convention for React Apps - is it common practice to start a file name with a capital letter?

2021-03-23 11:24 UTC, JuliaKholodetska commented on client/src/App.js
> +        <footer className="row center">All right reserved</footer>
> I'm not aware of file naming convention for React Apps - is it common practice to start a file name with a capital letter?

I can't say 100% that this is a common practice, although most tutorials call it the same.

2021-03-23 11:29 UTC, JuliaKholodetska commented
> * I suggest re-thinking the project file structure.
> * the image formats are strange.
> * why are there 2 `index.html` files in your project?
> * I do not see the root element

>the format of the photos is because I took it from the site.
>I remove the folder template, just so convenient, first I made a design layout there, and then moved it to the reactor. ('I suggest re-thinking the project file structure.' this has also changed)

2021-03-24 07:39 UTC, MariiaKolisnyk requested changes

2021-03-24 07:39 UTC, MariiaKolisnyk commented on client/src/index.css
> +  margin: 1rem;
honestly, I have not seen before using `rem` for radius/margin/padding properties. I suggest using `px`. but it's up to you if you are following the same units everywhere, since I still see a mix of units.

2021-03-24 07:39 UTC, MariiaKolisnyk commented on client/src/index.css
> +.card-body>* {
`.card-body > *`

2021-03-24 07:39 UTC, MariiaKolisnyk commented on client/src/screens/HomeScreen.js
> +import React from 'react'
I'm assume that `screens` should be `pages`.

2021-03-24 07:39 UTC, MariiaKolisnyk commented on client/src/screens/ProductScreen.js
> +    const product = data.products.find(x => x.id === props.match.params.id);
code formating

2021-03-24 09:38 UTC, MariiaKolisnyk requested changes

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/components/Rating.js
> +    let ratings = [];
`ratings` could be `const` since you are not change it.
please, add an empty line after variables declaration block.

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/index.css
> +  margin-bottom: 0.2 rem;
`0.2 rem` - remove extra space please.

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/components/Product.js
> +}
code formating

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/pages/ProductPage.js
> +export default function ProductScreen(props) {
ProductScreen should be renamed accordingly to the file name (please check all the Components)

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/components/Rating.js
> +            <span>{numReviews >= 1 ? numReviews + ' reviews' : ' '}</span>
oh, I didn't mean this. you can leave whatever you want.
but if I were implementing this, I would do the following:
```
<span>{numReviews = 0 ? 'no reviews yet' :  numReviews = 1 ? '1 review' : numReviews + ' reviews'}</span>
```

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/App.js
> +    <BrowserRouter>
we agreed to use 4 space indent

2021-03-24 09:38 UTC, MariiaKolisnyk commented on client/src/App.js
> +            <a className="brand" href="index.html">Beauty Beach</a>
`href="index.html"` 
I'm not sure about this. do you mean to navigate to the homepage? shouldn't we use Routing for this purpose?

2021-03-24 20:12 UTC, MariiaKolisnyk requested changes
I'm sorry I'm still see inconsistent code formatting. I have some concerns as for CSS as well.
Let's touch base tomorrow morning.

2021-03-25 08:41 UTC, MariiaKolisnyk approved these changes

2021-03-25 09:51 UTC, merged